### ISSUE TITLE
Is the course published yet?

### ISSUE THREAD

**Issue by 274188A** [KevinDockx/DealingWithCredentialsWhenSecuringAspNetCore3#1]
Hi Kevin, The latest course I can find of your is Feb 20

![image](https://user-images.githubusercontent.com/40014477/77495258-fc8b1a80-6e82-11ea-8462-9e34a3a9431a.png)

Still in progress I assume.

Looking forward to it - J

**Comment by WisdomCorp** [comment]
Yes its published 27th April 2020
